#!/bin/bash
# hook: pre-release-check
# version: 3.1.0
# event: Manual
# description: Dispatcher for mechanized pre-release gates (issue #558) — runs every *.sh script under its own release-gates/ subdirectory that is on the allowlist (built-in gates plus any project-authored custom gates explicitly opted in) and whose SHA-256 checksum matches release-gates/.sha256-checksums (fail-closed integrity verification, issue #603), collects pass/fail, invoked explicitly by the release agent before tagging/pushing a release, not fired automatically by native tool events
# enabled_by_default: false

# NOTE on `event: Manual`: unlike this repo's other hooks, this script is NOT
# meant to be registered in settings.json via
#   .meta-config/project.yaml: hooks: { pre-release-check: { enabled: true } }
# (that mechanism only wires up native Claude-Code events like PreToolUse).
# Its mere presence at <provider-hooks-dir>/pre-release-check.sh is enough —
# the `release` agent checks for the file itself and runs it with Bash
# before cutting a release. See agents/1-generic/release.md and
# docs/RELEASE_GATES.md.
#
# --- Plugin architecture (issue #558) ---
# This script itself contains NO gate logic and does NOT decide which gates
# are active — it is a pure dispatcher. Every *.sh file directly inside the
# release-gates/ directory next to this script that is ALSO on the
# allowlist (see below, issue #598) is executed in turn:
#   - Built-in gates ship from hooks/1-generic/release-gates/ in agent-meta
#     and are deployed here by sync.py (scripts/lib/hook_plugins.py::
#     sync_release_gates()), which also (re)writes release-gates/
#     .agent-meta-managed — the allowlist entry for built-ins — and
#     release-gates/.sha256-checksums (issue #603, see below).
#   - Projects extend the pipeline by dropping their own *.sh files into
#     <hooks_dir>/release-gates/ AND explicitly listing the filename in
#     release-gates/.allowed-gates (sync.py never touches or removes either
#     the script or this manifest, exactly like project-owned hooks created
#     via --create-hook). No framework change required to add a
#     project-specific gate — one manifest line is.
# Each gate script decides for itself whether it is enabled (reads its own
# baked-in default / env var / config) and whether its prerequisites are met
# (missing config/tool → self-skip, exit 0). This dispatcher only cares
# about the final exit code of each ALLOWED script: 0 = pass (incl.
# self-skip), non-zero = fail. See docs/RELEASE_GATES.md for the full gate
# contract and a copy-paste example for writing a custom gate.
#
# Exit 0 = every allowed gate script exited 0 (passed or self-skipped).
# Exit 1 = at least one allowed gate script exited non-zero, or was refused
#          by the checksum verification below (fail-closed, issue #603) —
#          release must be aborted.

set -uo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-$PWD}"
cd "$PROJECT_ROOT" || exit 1

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GATES_DIR="$SCRIPT_DIR/release-gates"

if [ ! -d "$GATES_DIR" ]; then
  echo "pre-release-check: no $GATES_DIR directory found — nothing to run, nothing configured."
  exit 0
fi

# --- Allowlist (issue #598) -----------------------------------------------
# Running every *.sh dropped into release-gates/ unconditionally was a
# supply-chain risk: a file placed there accidentally, via a compromised
# dependency, or a malicious PR would run automatically as part of the
# release process with no allowlist or integrity check. The allowlist is the
# union of two manifests, each one filename per line, '#'-comments and blank
# lines ignored:
#   - release-gates/.agent-meta-managed  — framework-shipped built-ins,
#     written by sync.py. Trusted because they come from the agent-meta
#     source tree, never from an arbitrary drop-in.
#   - release-gates/.allowed-gates       — project-owned manifest, sync.py
#     NEVER writes or deletes this file. A project opts a custom gate in by
#     adding its filename here.
# A *.sh present in release-gates/ but listed in NEITHER manifest is
# skipped with a [SKIP] line — not silently run, and not treated as a
# release-blocking failure (a stray/experimental script shouldn't itself
# abort a release; the whole point is that it doesn't run at all).
#
# --- Checksum integrity (issue #603) ---------------------------------------
# The allowlist controls WHICH gate scripts may run — not whether their
# content is still what was deployed. Before executing an allowlisted gate,
# this dispatcher compares the file's SHA-256 checksum against
# release-gates/.sha256-checksums (sha256sum-compatible: '<hash>  <filename>'
# lines, '#'-comments and blank lines ignored):
#   - Built-in gates: the manifest is (re)generated by sync.py
#     (scripts/lib/hook_plugins.py::sync_release_gates()) — never edit it
#     by hand; re-running sync.py refreshes it.
#   - Project-owned gates: the project replaces/adds the checksum line
#     itself, e.g.
#       (cd "$GATES_DIR" && sha256sum my-check.sh >> .sha256-checksums)
# Fail-closed (issue #603 decision): a gate is refused — and the release
# blocked — when the manifest is missing, when the gate has no checksum
# entry, when the checksum does not match (content changed after
# deployment), or when no SHA-256 tool is available. A blocked release is
# recoverable; an unnoticed tampered gate in the release path is not.
# Escape hatch after INTENTIONAL changes: re-run sync.py (built-in gates)
# or replace the gate's checksum line (project gates) — see
# docs/RELEASE_GATES.md. NOTE: like the allowlist, this manifest is a
# convention boundary, not a security boundary — anyone able to rewrite a
# gate script on disk can also rewrite its checksum line; the verification
# catches accidental/drive-by modifications and forces an explicit,
# visible re-registration step for intentional ones.
_read_gate_manifest() {
  local f="$1"
  [ -f "$f" ] || return 0
  local line stripped
  while IFS= read -r line || [ -n "$line" ]; do
    stripped="${line%%#*}"
    stripped="$(printf '%s' "$stripped" | tr -d '[:space:]')"
    [ -n "$stripped" ] && printf '%s\n' "$stripped"
  done < "$f"
}

ALLOWLIST=$(
  {
    _read_gate_manifest "$GATES_DIR/.agent-meta-managed"
    _read_gate_manifest "$GATES_DIR/.allowed-gates"
  } | sort -u
)

_gate_is_allowed() {
  printf '%s\n' "$ALLOWLIST" | grep -qxF "$1"
}

CHECKSUM_MANIFEST=".sha256-checksums"

_file_sha256() {
  # Print the SHA-256 hex digest of file $1; fail (non-zero, no output)
  # when no hashing tool is available or the file cannot be read.
  local f="$1" out
  if command -v sha256sum >/dev/null 2>&1; then
    out="$(sha256sum -- "$f" 2>/dev/null)" || return 1
  elif command -v shasum >/dev/null 2>&1; then
    out="$(shasum -a 256 -- "$f" 2>/dev/null)" || return 1
  else
    return 1
  fi
  printf '%s\n' "${out%% *}"
}

_stored_gate_hash() {
  # Print the checksum stored for gate filename $1 in the checksum manifest;
  # return non-zero when the manifest is missing or has no entry for $1.
  local hash name
  [ -f "$GATES_DIR/$CHECKSUM_MANIFEST" ] || return 1
  while read -r hash name _rest || [ -n "$hash" ]; do
    case "$hash" in
      ''|'#'*) continue ;;  # blank line or comment
    esac
    if [ "$name" = "$1" ]; then
      printf '%s\n' "$hash"
      return 0
    fi
  done < "$GATES_DIR/$CHECKSUM_MANIFEST"
  return 1
}

_checksum_remediation_hint() {
  # $1 = gate filename, $2 = "missing" (no checksum entry) or "changed"
  # (checksum mismatch). Ownership split per issue #598 decides the hint:
  # sync-managed gates are fixed by re-running sync.py, project-owned gates
  # by re-registering their checksum line.
  local gate_file="$1" mode="$2"
  if _read_gate_manifest "$GATES_DIR/.agent-meta-managed" | grep -qxF "$gate_file"; then
    printf '       Remediation: built-in gate "%s" — re-run sync.py in the project root; it redeploys built-in gates and regenerates %s. If the modification was NOT intentional, investigate how the file changed before re-deploying.\n' \
      "$gate_file" "$CHECKSUM_MANIFEST"
  elif [ "$mode" = "missing" ]; then
    printf '       Remediation: project-owned gate "%s" — add its checksum line: (cd "%s" && sha256sum "%s" >> %s)\n' \
      "$gate_file" "$GATES_DIR" "$gate_file" "$CHECKSUM_MANIFEST"
  else
    printf '       Remediation: project-owned gate "%s" — replace its stale line in %s with the output of: (cd "%s" && sha256sum "%s"); otherwise restore the original file.\n' \
      "$gate_file" "$CHECKSUM_MANIFEST" "$GATES_DIR" "$gate_file"
  fi
}

_verify_gate_integrity() {
  # $1 = path to the gate script. Return 0 = safe to execute; 1 = refused
  # (fail-closed, reason + remediation already printed). Issue #603.
  local gate_path="$1" gate_file expected actual
  gate_file="$(basename "$gate_path")"

  if [ ! -f "$GATES_DIR/$CHECKSUM_MANIFEST" ]; then
    echo "[FAIL] $gate_file: $CHECKSUM_MANIFEST missing in $GATES_DIR — refusing to run release gates (fail-closed, issue #603)."
    echo "       Remediation: re-run sync.py in the project root to regenerate the checksum manifest for built-in gates; for project-owned gates see docs/RELEASE_GATES.md."
    return 1
  fi

  expected="$(_stored_gate_hash "$gate_file")"
  if [ -z "$expected" ]; then
    echo "[FAIL] $gate_file: no checksum entry in $CHECKSUM_MANIFEST — refusing to run (fail-closed, issue #603)."
    _checksum_remediation_hint "$gate_file" missing
    return 1
  fi

  actual="$(_file_sha256 "$gate_path")"
  if [ -z "$actual" ]; then
    echo "[FAIL] $gate_file: no SHA-256 tool available (need sha256sum or shasum in PATH) — refusing to run release gates (fail-closed, issue #603)."
    return 1
  fi

  if [ "$actual" != "$expected" ]; then
    echo "[FAIL] $gate_file: SHA-256 checksum mismatch (manifest: $expected, file: $actual) — the gate script changed after deployment. Refusing to run (fail-closed, issue #603)."
    _checksum_remediation_hint "$gate_file" changed
    return 1
  fi

  return 0
}

FAILED_GATES=()
SKIPPED_GATES=()
RAN_ANY=false

for gate_script in "$GATES_DIR"/*.sh; do
  [ -e "$gate_script" ] || continue  # literal glob with no matches
  gate_file="$(basename "$gate_script")"

  if ! _gate_is_allowed "$gate_file"; then
    echo "[SKIP] $gate_file: not on the release-gates allowlist — add it to $GATES_DIR/.allowed-gates to enable it (issue #598)."
    SKIPPED_GATES+=("$gate_file")
    continue
  fi

  RAN_ANY=true
  gate_name="$(basename "$gate_script" .sh)"

  # Integrity check BEFORE execution (issue #603, fail-closed): a gate whose
  # content does not match its registered checksum never runs.
  if ! _verify_gate_integrity "$gate_script"; then
    FAILED_GATES+=("$gate_name (checksum)")
    echo ""
    continue
  fi

  echo "=== Running gate: $gate_name ==="
  if ! bash "$gate_script"; then
    FAILED_GATES+=("$gate_name")
  fi
  echo ""
done

if [ "$RAN_ANY" = "false" ]; then
  if [ "${#SKIPPED_GATES[@]}" -gt 0 ]; then
    echo "pre-release-check: $GATES_DIR has ${#SKIPPED_GATES[@]} script(s) but none are on the allowlist — nothing ran."
  else
    echo "pre-release-check: $GATES_DIR is empty — nothing to run."
  fi
  exit 0
fi

echo "=== Pre-Release Gate Dispatcher Summary ==="
if [ "${#SKIPPED_GATES[@]}" -gt 0 ]; then
  echo "NOTE: ${#SKIPPED_GATES[@]} script(s) skipped (not on allowlist): ${SKIPPED_GATES[*]}"
fi
if [ "${#FAILED_GATES[@]}" -gt 0 ]; then
  echo "RESULT: FAILED — ${#FAILED_GATES[@]} gate(s) blocked the release:"
  for g in "${FAILED_GATES[@]}"; do
    echo "  - $g"
  done
  exit 1
fi

echo "RESULT: all release gates passed"
exit 0
